### ISSUE TITLE
Question about the predict of Demo_unet3d.py

### ISSUE THREAD

**Issue by StefanieWang123** [KiPA2022/kipa22#3]
Hi very nice work and thanks a lot for the baseline released. I have learnt a lot from it.
But I have a question about the predict . After I finish the unet3d model training, I want to use the model to predict new images, Set the following:
is_load=True,
is_train=False,
load_epoch=200,
There's a problem

Predict test data
amos_0001.nii.gz
Traceback (most recent call last):
  File "Demo_unet3d.py", line 153, in <module>
    predict(net_S, pred_dir, test_dir + '/image', model_name)
  File "Demo_unet3d.py", line 107, in predict
    predict= model(image).data.cpu().numpy()
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/code/kipa22-main/BASELINES/models/UNet3D.py", line 90, in forward
    x = self.unet(x)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/code/kipa22-main/BASELINES/models/UNet3D.py", line 79, in forward
    x = self.up4(x, x1)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/code/kipa22-main/BASELINES/models/UNet3D.py", line 38, in forward
    return self.conv(x)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/code/kipa22-main/BASELINES/models/UNet3D.py", line 18, in forward
    return self.double_conv(x)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangsifan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 521, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 273.38 GiB (GPU 0; 31.72 GiB total capacity; 25.81 GiB already allocated; 2.34 GiB free; 28.07 GiB reserved in total by PyTorch)

Hope to hear from you. Thank you so much.

**Comment by KiPA2022** [comment]
Hi,

Thank you for this issue. 

1. This is because your GPU memory is smaller than the testing requirement, so this program reported this issue. More details can be found on the PyTorch official web: https://pytorch.org/docs/master/notes/faq.html#my-model-reports-cuda-runtime-error-2-out-of-memory.
2. We found the testing image is "amos_0001.nii.gz" whose size is much larger than the images in our challenge, maybe some pre-processing operations are required (e.g., crop).

Sincerely，
KiPA22 Group
